### ISSUE TITLE
OMG Issue 17073: Changeable/ChangeDescription typo

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#10]
http://www.omg.org/issues/cts2-ftf.html#Issue17073

sucessor -> successor

**Comment by kevinpeterson** [comment]
### Reason For Change

Typographical error in specification documentation.

### Severity: Support Text

### Proposed Resolution (PIM)

Update PIM diagram

### Proposed Resolution (PSM)

NA

#### Change Location: Core Information Model, Page 30.

#### Description

Updated diagram "class Updates" to modify the text of the relationship between 'Changeable' and 'ChangeDescription' to be:

```
successor
```

instead of:

```
sucessor
```
