### ISSUE TITLE
OMG Issue 17434: Delta stereotype is opposite of isQuery

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#111]
The  stereotype indicates that the operation may change the service state, which is the opposite of the UML isQuery tag.  You need to set the isQuery tag to true on all non-delta operations and then include documentation on each  operation to repeat what it means because everyone will ignore it otherwise.

http://www.omg.org/issues/cts2-ftf.html#Issue17434

**Comment by hsolbrig** [comment]
Added "isQuery='true'" to all non-delta operations, which changes all interface diagrams containing methods to include "{query}" after the method description.  Added the line "This operation may alter the state of the service." immediately after the method description for all delta methods to help people remember what "delta" means.

**Comment by kevinpeterson** [comment]
### Reason For Change

The stereotype indicates that the operation may change the service state, which is the opposite of the UML isQuery tag. You need to set the isQuery tag to true on all non-delta operations and then include documentation on each operation to repeat what it means because everyone will ignore it otherwise.

### Severity: Significant

### Proposed Resolution (PIM)

Added "isQuery='true'" to all non-delta operations, which changes all interface diagrams containing methods to include "{query}" after the method description. Added the line "This operation may alter the state of the service." immediately after the method description for all delta methods to help people remember what "delta" means.

Added "This operation may alter the state of the service." in the following locations:

CodeSystems.pdf
3.4.1
3.4.1.2
5.4.1.1
5.4.1.2

ConceptDomain.pdf
3.4.1.1
3.4.1.2

Core.pdf
3.3.4.2
3.3.4.5
3.3.4.6
3.3.4.7
3.3.4.8
3.3.4.9
3.4.2.2
3.2.4.10
3.4.2.15
3.4.3.5

Entity.pdf
3.4.1.1
3.4.1.2
3.4.1.3
3.4.1.4
3.4.1.5
3.4.1.6
3.4.1.7
3.4.1.8
3.4.1.9
3.4.1.10
5.1.4.2
5.1.4.3
5.1.4.4

Map.pdf
3.4.1.1
3.4.1.2
5.4.2.2
5.4.2.3
6.4.1.1
6.4.1.2
6.4.1.3
6.4.1.4
6.4.1.5
6.4.1.6
6.4.1.7

ValueSet.pdf
3.4.2.1
3.4.2.2
5.4.1.1
5.4.1.2
5.4.1.3
5.4.1.4
5.4.1.5
5.4.1.6
5.4.1.7
5.4.1.8
5.4.1.9
5.4.1.10
5.4.1.11
5.4.1.12
5.4.1.13
7.1.1.1
7.1.1.2
7.1.1.3
7.1.1.4
7.2.1.1
7.2.1.2
7.3.1.1
7.3.1.2
7.3.1.3
7.3.1.4
7.3.1.5
7.3.1.6

### Proposed Resolution (PSM)

N/A
