### ISSUE TITLE
OMG Issue 17118: ResolvedValueSetReadService and QueryService omitted from spec

### ISSUE THREAD

**Issue by hsolbrig** [cts2/cts2-specification#40]
http://www.omg.org/issues/cts2-ftf.html#Issue17118

ResolvedValueSet needs two additional service entries - a read service that carries:
read (by RVS URI)
resolveAsEntityDirectory
resolveAsCompleteSet

(Same methods as the ValueSetResolutionService except that the argument is a single ResolvedValueSetURI)

and a simple query service that carries:
contains(resolvedSet, EntityNameOrURIList  (move from loader)
resolvedSetsFor(EntityNameOrURI, ...)   -> tells which resolved sets carry the entity

**Comment by kevinpeterson** [comment]
I'm not sure that we can accommodate a "resolveAsEntityDirectory" method on a ResolvedValueSet Service. A ResolvedValueSet contains a collection of 'EntitySynopsis's -- and 'resolveAsEntityDirectory' would mean the service would have to translate those 'EntitySynopsis' objects into 'EntityDirectoryEntry's. Specifically, I don't know how we would populate the 'knownEntityDescription' field of the 'EntityDirectoryEntry.' In a ResolvedValueSet, we know which CodeSystemVersion(s) the content came from, but given a single 'EntitySynopsis', we have no way of knowing which CodeSystemVersion it came from.

The question is, if a services imports a ResolvedValueSet xml from another service, is there enough information in that ResolvedValueSet xml to produce a EntityDirectory?

**Comment by hsolbrig** [comment]
Good point.  There is definitely a need to get from a resolved value set back to the entity descriptions so that the content of the value set can be represented as a graph, be accompanied by definitions, etc.  That said, a service obviously can't do this if they don't have the code system version.  I would propose that we add documentation that says that resolveAsEntityDirectory requires both the RVS and Entity profiles to work?

**Comment by kevinpeterson** [comment]
### Reason For Change

ResolvedValueSetReadService and QueryService functionality was omitted from spec.

### Severity: Significant

### Proposed Resolution (PIM)
1. Introduce a new type - 'IterableResolvedValueSet' - and change the 'ResolvedValueSetDirectoryEntry' to be a subtype of 'ResolvedValueSetSummary.'
   Updated Diagram (Figure 3.4: Resolved ValueSet. Value Set Definition, Page 27.)
   ![Figure 3.4: Resolved ValueSet. Value Set Definition, Page 27.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/05/ResolvedValueSet.png)
2. Added a new service, 'ResolvedValueSetResolution' Service, which follows the same general resolution patterns as  'ValueSetDefinitionResolution' service. The 'contains' method is moved from 'ResolvedValueSetLoader' to this new 'ResolvedValueSetResolution' service.
   Updated Diagram (Figure 5.1: Value Set Resolution Service. Value Set Definition, Page 46.)
   ![Figure 5.1: Value Set Resolution Service. Value Set Definition, Page 46.](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/05/ValueSetDefinitionResolution.png)
3. Add a new type of DirectoryURI, "ResolvedValueSetDirectoryURI.  Updated Diagram (Figure is only in UML model?)
   ![New Diagram](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/05/DirectoryTypes.png)
4. In order to query for 'ResolvedValueSets', a new service - 'ResolvedValueSetQuery' Service was added
   New Diagram
   ![New Diagram](http://informatics.mayo.edu/cts2/framework/wp-content/uploads/2012/05/ResolvedValueSetQueryService.png)

### Proposed Resolution (PSM)

#### Change Location: CoreService.xsd

#### Description

Added an 'IterableResolvedValueSet' type.

#### Updated XML

``` xml
    <xs:element name="IteratableResolvedValueSet" type="IteratableResolvedValueSet"/>
    <xs:complexType name="IteratableResolvedValueSet">
        <xs:annotation>
            <xs:documentation>A ResolvedValueSet whose contents are available as a set of directory entries that allows iteration.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="core:Directory">
                <xs:sequence>
                    <xs:element name="resolutionInfo" type="ResolvedValueSetHeader" minOccurs="1" maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>the set of parameters that were used in the resolution of this set. <i>resolutionInfo</i> provides all the information necessary to recreate the actual <i>resolution</i> when presented to a
                                    CTS<sub>2</sub> service instance that contains all of the necessary definitions and code system versions.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="entry" type="core:EntitySynopsis" minOccurs="0" maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>a synopsis of the <i>EntityDescription</i> that has been determined to be a member of the value set named in <i>resolutionInfo</i> according to the stated criteria or "bindings"</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
```
