### ISSUE TITLE
OMG Issue 17119: Refactor inline XSD types from WSDLs (SOAP PSM)

### ISSUE THREAD

**Issue by cts2** [cts2/cts2-specification#41]
http://www.omg.org/issues/cts2-ftf.html#Issue17119

All CTS2 WSDLs contain inline XSD type definitions. We would like to refactor those out into seperate XSD files in order to make code generation easier for tooling (mainly, Castor).

**Comment by kevinpeterson** [comment]
### Reason For Change

All CTS2 WSDLs contain inline XSD type definitions. We would like to refactor those out into seperate XSD files in order to make code generation easier for tooling (mainly, Castor).

### Severity: Significant

Logically, there is no effect on the WSDLs -- this is strictly a refactoring. There will be, however a number of additional artifacts as there will be one XSD per WSDL. This was significant in that some tooling had difficulty generating code from the WSDLs, and that could limit client uptake.

### Proposed Resolution (PIM)

NA

### Proposed Resolution (PSM)

#### Change Location: *.wsdl (every WSDL file)

#### Description

XSD declarations inside of WSDL files were making it difficult for tooling to process and generate code from the WSDL files. To work around this, and to make a clean separation between WSDL 'types' and WSDL 'functionality', all types that were previously inlined into the wsdl via the wsdl:types tag have been refactored into an XSD file.

#### Original XML

``` xml
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" ...>
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:core="http://schema.omg.org/spec/CTS2/1.0/Core" xmlns:association="http://schema.omg.org/spec/CTS2/1.0/Association" xmlns:coreService="http://schema.omg.org/spec/CTS2/1.0/CoreService" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://schema.omg.org/spec/CTS2/1.0/wsdl/AssociationTransformServices">
      <xs:import namespace="http://schema.omg.org/spec/CTS2/1.0/Core" schemaLocation="http://informatics.mayo.edu/svn/trunk/cts2/spec/psm/rest/schema/Core.xsd"/>
      <xs:import namespace="http://schema.omg.org/spec/CTS2/1.0/CoreService" schemaLocation="http://informatics.mayo.edu/svn/trunk/cts2/spec/psm/rest/serviceSchema/CoreService.xsd"/>
      <xs:import namespace="http://schema.omg.org/spec/CTS2/1.0/Association" schemaLocation="http://informatics.mayo.edu/svn/trunk/cts2/spec/psm/rest/schema/Association.xsd"/>
      <xs:import namespace="http://schema.omg.org/spec/CTS2/1.0/wsdl/BaseServiceTypes" schemaLocation="http://informatics.mayo.edu/svn/trunk/cts2/spec/psm/soap/wsdl/BaseServiceTypes.xsd"/>
    ...
  </wsdl:types>
```

#### Updated XML

Everything in the wsdl:types tag was refactored into a {WSDLName}Types.xsd file.

Sample Types.xsd file:

``` xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" ... >
   {insert here everything from the <wsdl:types> tag in the WSDL}
</xs:schema>
```
