### ISSUE TITLE
OMG Issue 17185: AssociationMaintenanceServices WSDL corrections

### ISSUE THREAD

**Issue by cts2** [cts2/cts2-specification#54]
http://www.omg.org/issues/cts2-ftf.html#Issue17185
- In method 'putChangeSet' add param 'errorResponse'
- In method 'validateChangeSet' add param 'validationLevel'
- In method 'updateChangeSetMetadata' add param 'officialEffectiveDate'
- In method 'updateChangeableMetadata' remove params 'target' and 'owner' and add param 'entryID'
- Removed methods 'createAssociationsFromExpression' and 'createAssociationFromExpression'
- Added method 'addAssociation
- Added params 'subject', 'predicate', 'target', 'ecternalStatementId' to method 'updateAssociation;

**Comment by kevinpeterson** [comment]
### Reason For Change

The method 'putchangeSet' was changed to a 'ProcessStatus' from a 'SuccessIndicator' because a 'ProcessStatus' carries much more metadata about the process (including endtime, log error/warnings, etc), and it was very difficult to accurately describe to the client the status of the process using 'SuccessIndicator' because it was very non-descriptive.

The method 'validateChangeSet' needs a 'validationLevel' to align with the PIM and allow a client to set the requested validation type.

In method 'updateChangeSetMetadata' the param 'officialEffectiveDate' was omitted as a WSDL generation error.

In method 'updateChangeableMetadata' the param 'entryID' is needed to uniquely identify the resource to be changed. With that, 'target' and 'owner' become unnecessary.

Removed methods 'createAssociationsFromExpression' and 'createAssociationFromExpression' to align with the PIM.

An 'add' method is necessary for Associations ('addAssociation') in order to explicitly assert a new association.

The method 'updateAssociation' was not generated with the complete set of updatable params -- added 'subject', 'predicate', 'target', 'externalStatementId.'

### Severity: Minor

### Proposed Resolution (PIM)

NA

### Proposed Resolution (PSM)

#### Change Location: AssociationMaintenanceService.wsdl, AssociationMaintenanceServiceTypes.xsd

#### Description

Added or removed parameters as follows:
- In method 'putChangeSet' add param 'errorResponse'
- In method 'validateChangeSet' add param 'validationLevel'
- In method 'updateChangeSetMetadata' add param 'officialEffectiveDate'
- In method 'updateChangeableMetadata' remove params 'target' and 'owner' and add param 'entryID'
- Removed methods 'createAssociationsFromExpression' and 'createAssociationFromExpression'
- Added method 'addAssociation
- Added params 'subject', 'predicate', 'target', 'externalStatementId' to method 'updateAssociation;

#### Updated XML

File: AssociationTransformService.wsdl

``` xml
---Added---->
  <wsdl:message name="addAssociation">
    <wsdl:part name="parameters" element="tns:addAssociation"/>
  </wsdl:message>

  <wsdl:message name="addAssociationResponse">
    <wsdl:part name="parameters" element="tns:addAssociationResponse"/>
  </wsdl:message>
---End Added---->

---Removed---->
  <wsdl:message name="createAssociationFromExpressionResponse">
    <wsdl:part name="parameters" element="tns:createAssociationFromExpressionResponse"/>
  </wsdl:message>

  <wsdl:message name="createAssociationsFromExpressionResponse">
    <wsdl:part name="parameters" element="tns:createAssociationsFromExpressionResponse"/>
  </wsdl:message>

  <wsdl:message name="createAssociationFromExpression">
    <wsdl:part name="parameters" element="tns:createAssociationFromExpression"/>
  </wsdl:message>

  <wsdl:message name="createAssociationsFromExpression">
    <wsdl:part name="parameters" element="tns:createAssociationsFromExpression"/>
  </wsdl:message>
---End Removed---->

```

File: AssociationTransformServiceTypes.xsd

``` xml
  <xs:complexType name="putChangeSet">
    <xs:sequence>
      <xs:element minOccurs="1" name="changeSet" type="core:ChangeSetURI"/>
---Added--->     <xs:element minOccurs="0" name="errorResponse" type="coreService:ErrorResponse"/>
    </xs:sequence>

  </xs:complexType>

```

``` xml
  <xs:complexType name="validateChangeSet">
    <xs:sequence>
---Added--->      <xs:element minOccurs="1" name="validationLevel" type="coreService:ValidationLevel"/>
      <xs:element minOccurs="1" name="changeSet" type="updates:ChangeSet"/>
    </xs:sequence>

  </xs:complexType>

```

``` xml
  <xs:complexType name="updateChangeSetMetadata">
    <xs:sequence>
      <xs:element minOccurs="1" name="changeSet" type="core:ChangeSetURI"/>
      <xs:element minOccurs="0" name="creator" type="core:SourceReference"/>
      <xs:element minOccurs="0" name="changeInstructions" type="core:OpaqueData"/>
---Added--->      <xs:element minOccurs="0" name="officialEffectiveDate" type="core:DateAndTime"/>
    </xs:sequence>

  </xs:complexType>
```

``` xml
  <xs:complexType name="updateChangeableMetadata">
    <xs:sequence>
      <xs:element minOccurs="1" name="changeSet" type="core:ChangeSetURI"/>
---Added--->      <xs:element minOccurs="1" name="entryID" type="core:PersistentURI" />
      <xs:element minOccurs="0" name="status" type="coreService:NameOrURI"/>
      <xs:element minOccurs="0" name="entryState" type="core:EntryState"/>
    </xs:sequence>

  </xs:complexType>
```

``` xml
  <xs:complexType name="updateAssociation">
    <xs:sequence>
      <xs:element minOccurs="1" name="changeSet" type="core:ChangeSetURI"/>
      <xs:element minOccurs="1" name="assertingCodeSystemVersion" type="coreService:NameOrURI"/>
      <xs:element minOccurs="1" name="subject" type="coreService:EntityNameOrURI"/>
---Added--->      <xs:element minOccurs="1" name="predicate" type="coreService:EntityNameOrURI"/>
---Added--->      <xs:element minOccurs="1" name="target" type="core:StatementTarget"/>
---Added--->      <xs:element minOccurs="0" name="externalStatementId" type="core:String"/>
    </xs:sequence>

  </xs:complexType>

```
