### ISSUE TITLE
OMG Issue 17186: AssociationTransformServices WSDL corrections

### ISSUE THREAD

**Issue by cts2** [cts2/cts2-specification#55]
http://www.omg.org/issues/cts2-ftf.html#Issue17186
- Removed method 'getSupportedVersionTags' and 'fromEntityDirectory'
- In method 'toAssociationFormat' changed type of param 'codeSystemVersion' to 'CodeSystemVersionReference'

**Comment by kevinpeterson** [comment]
### Reason For Change

In method 'toAssociationFormat' changed type of param 'codeSystemVersion' to 'CodeSystemVersionReference' - caused by a typo in the WSDL and changing to allow for better alignment with the PIM. The method 'getSupportedVersionTags' was refactored into a base class and 'fromEntityDirectory' was redundant with a method in the 'EntityTransformService.'

### Severity: Minor

### Proposed Resolution (PIM)

NA

### Proposed Resolution (PSM)

#### Change Location: AssociationTransformService.wsdl,AssociationTransformServiceTypes.xsd

#### Description

Removed method 'getSupportedVersionTags' and 'fromEntityDirectory'
- Reason: Refactored into BaseService

In method 'toAssociationFormat' changed type of param 'codeSystemVersion' to 'CodeSystemVersionReference'
- Reason: Typo

#### Original XML

``` xml
NOTE: (for removes see below)
 (AssociationTransformServiceTypes.xsd)
  <xs:complexType name="toAssociationFormat">
    <xs:sequence>
      <xs:element minOccurs="1" name="entityExpression" type="core:EntityExpression"/>
---Modified----> <xs:element minOccurs="1" name="codeSystemVersion" type="coreService:NameOrURI"/>
    </xs:sequence>
```

#### Updated XML

**Note: elements in this section have been removed from the original.**

``` xml

---Modify--->
  <xs:complexType name="toAssociationFormat">
    <xs:sequence>
      <xs:element minOccurs="1" name="entityExpression" type="core:EntityExpression"/>
---Modified----> <xs:element minOccurs="1" name="codeSystemVersion" type="core:CodeSystemVersionReference"/>
    </xs:sequence>
---End Modify--->

---Remove--->
  <wsdl:message name="getSupportedVersionTags">
    <wsdl:part name="parameters" element="tns:getSupportedVersionTags"/>
  </wsdl:message>

  <wsdl:message name="getSupportedVersionTagsResponse">
    <wsdl:part name="parameters" element="tns:getSupportedVersionTagsResponse"/>
  </wsdl:message>
---End Remove-->

---Remove--->
    <wsdl:operation name="getSupportedVersionTags">
      <wsdl:input name="getSupportedVersionTags" message="tns:getSupportedVersionTags"/>
      <wsdl:output name="getSupportedVersionTagsResponse" message="tns:getSupportedVersionTagsResponse"/>
    </wsdl:operation>
---End Remove-->

---Remove--->
    <wsdl:operation name="getSupportedVersionTags">
      <documentation xmlns="http://schemas.xmlsoap.org/wsdl/"/>
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getSupportedVersionTags">
        <soap:body use="literal"/>
      </wsdl:input>

      <wsdl:output name="getSupportedVersionTagsResponse">
        <soap:body use="literal"/>
      </wsdl:output>

    </wsdl:operation>
---End Remove-->

```
