### ISSUE TITLE
Alignment definitions "Entity" between the PIM and HL7 CTS2 SFM

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#66]
The PIM defines "entity" as “class”, “category”, “concept”, “predicate”, “property”, “term”, “individual”.  The HL7 CTS2 SFM differentiate between these concepts.  A CodeSystemEntity can be either an association (CodeSystemEntityAssociation) or a node (CodeSystemNode) - meaning either a concept (CodeSystemConcept), or a code (CodeSystemConceptCode).  However, in the HL7 SFM, an entity cannot be a property - the DefinedEntityProperty class is part of the Code Sytem class (in the same way that entities are), and the EntityPropertyVerion class is part of the CodeSystemEntityVersion.  The two definitions of "entity" - in PIM and HL7 CTS2 DSTU are different.  Proposition:  explain the rationale for the difference in the definitions and document it so that it is coherent between the two sets of documents.

**Comment by hsolbrig** [comment]
Note that the PIM also differentiates these various types of entity as well.   The choice of "entity" was because of the confusion introduced by the use of "concept" (as, isn't _everything_ a concept?), as well as "code" in the SFM, which seems to sit somewhere between a simple identifier and a full-fledged "concept".   "Entity" was chosen specifically because it had already been adopted by the W3C in the OWL 2 specification.  The use of "property" in this context is the RDF and OWL notion of property, which are defined as subclasses of the Entity class in the OWL specification.

Will include a clarifying statement in the document regarding the etymology of these words.

**Comment by aestelrich** [comment]
We are not asking for the etymology of the words, we are asking for clarification on how these principles such as CodeSystemEntityAssociation, CodeSystemNode,CodeSystemConcept, or acode CodeSystemConceptCode are expressed by the PIM information model. 

For example how does the PIM information model support the abstract concept in HL7 which do not have a code such as InformationRecepient, RoleClass, RoleClassAssociative (HL7 Vocabulary has many examples such as these).
