### ISSUE TITLE
CD datatypes ISO 21090 replaced by enumerations

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#76]
In the Core Elements...The term “datatype” refers to “a type whose instances are identified only by their value.  This definition is oversimplified within the context of ISO21090.  ISO21090 is mentioned in the introductory document, hence the definition of a datatype should be more complex.  It seems that the CD datatypes are not used in the specifications, and enumerations are used whenever codes belonging to Code Systems are needed.

**Comment by hsolbrig** [comment]
You will note that the reference in the CTS2 specification is to an OMG modeling document.  While we would probably quibble as to whether the OMG definition (drawn from computer science) is "oversimplified" or, perhaps, 21090 is "overcomplicated", but the simple definition works for its purpose.  CD datatypes are not used because (a) CTS2 is not about healthcare data, it is about terminology and (b) 21090 is unknown and unused outside of the healthcare community.   Note that mappings from the CTS2 data types to 21090 will be provided at a later date for those who feel uncomfortable about simple strings without accompanying missing value reasons, etc.

**Comment by aestelrich** [comment]
Ok for not using ISO20190 and CD datatypes. 
However, a terminology service which itself uses coded data to indicate, for example, the resource type (such as in ResouceDescription), we have Resource Type and we have an enumeration “CTS2RessourceType” which contains 7 items.  This would be better managed through real code systems.
