### ISSUE TITLE
Multiply the object instances in order to represent the correct information

### ISSUE THREAD

**Issue by aestelrich** [cts2/cts2-specification#80]
« CTS2 differentiates between a simple resource reference, such as a code system, code system version, value set, etc. and a reference to an Entity - a class, predicate or individual. Simple resource references are identified by a single URI. Entity references, however, are subdivided into two parts - an scoping name space and a name that is unique within the context of the namespace. ».  

The identification of an object seems to be done via a combination between a Resource and an Entity. This construction does not cover easily the complexity of the identification of the objects as required by the HL7 SFM - for example a Code System and a Code System Version in the SFM have a compositional relationship - i.e. the Code System Version cannot exist independently from the Code System.  In the PIM a Code System version is a resource which points to the Resource Code System; however this construction  implies that a Code System Version has a unique resource identifier which is often not the case.  This can also be seen through another example. In the SFM there are objects whose identification is much more complex such as the value of an attribute of a LOINC code.  In order to correctly identify this value, we need to know at least four pieces of identification:  the OID of the Code System, the LOINC code itself, the identity of the attribute, and the version of the Code System.  The construct in the PIM leads to multiplying the object instances in order to represent the correct information.

**Comment by hsolbrig** [comment]
The SFM states a compositional relationship between Code Systems and Code System Versions.  The CTS2 specification, however, identifies <i>metadata</i> about code systems and code system versions.  While, obviously, it makes no sense to have a version of a code system without the code system itself, there is nothing in the CTS2 service that requires that descriptions of both of them be present.  The key is that the CTS2 does not contain code systems - it contains descriptions of code systems.  Similarly it doesn't contain code system versions - it contains descriptions of said versions.

The LOINC code example highlights this example.  "In order to correctly identify this value, we need ... the OID (or other unambiguous name - only HL7 does OIDs) of the Code system, the LOINC code itself (Scoped Entity Name LOINC:code), the identity of the attribute (URL of the Concept Domain) and the version of the code system (URL of the code system version).  CTS2 allows for all of these identifiers without requiring any sort of containment relationships - one can navigate from a the description of a code system to the various versions, etc., assuming that the service provider chooses to implement and respresent all of them.

**Comment by hsolbrig** [comment]
Follow up - what sort of change is this issue requesting?  If it is asking for the CTS2 specification to include the description of code system versions <i>inside</i> code system descriptions, this runs counter to the entire RESTful architectural model.  Is there something else here that I'm missing?

**Comment by aestelrich** [comment]
The attribute in question is not a Concept Domain.  Here we use an example  to better illustrate it.  In the LOINC code system for code 10375-4  we have about 50 attributes - and here we list only 6 of them: LOINC_NUM, COMPONENT, PROPERTY,TIME_ASPCT, SYSTEM with the respective values of:  10375-4, Irregularly contracted cells, ACnc, Pt, Bld.   How would the value Bld be expressed using the PIM?
